// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE_PetWeb_API.Models;

public partial class Appointment
{
    public int AppointmentId { get; set; }

    public int UserId { get; set; }

    public int PetId { get; set; }

    public int ServiceId { get; set; }

    public int? StaffId { get; set; }

    public DateTime AppointmentDate { get; set; }

    public DateTime? EndTime { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Pet Pet { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual Service Service { get; set; }

    public virtual Staff Staff { get; set; }

    public virtual User User { get; set; }
}