// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE_PetWeb_API.Models;

public partial class BlogPost
{
    public int PostId { get; set; }

    public int UserId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string FeaturedImage { get; set; }

    public string Category { get; set; }

    public string Tags { get; set; }

    public DateTime? PublishDate { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Status { get; set; }

    public int? ViewCount { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual User User { get; set; }
}