// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE_PetWeb_API.Models;

public partial class Comment
{
    public int CommentId { get; set; }

    public int PostId { get; set; }

    public int UserId { get; set; }

    public string Content { get; set; }

    public DateTime? CommentDate { get; set; }

    public bool? IsApproved { get; set; }

    public virtual BlogPost Post { get; set; }

    public virtual User User { get; set; }
}