// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE_PetWeb_API.Models;

public partial class MedicalRecord
{
    public int RecordId { get; set; }

    public int PetId { get; set; }

    public int? StaffId { get; set; }

    public DateTime? RecordDate { get; set; }

    public string Diagnosis { get; set; }

    public string Treatment { get; set; }

    public string Prescription { get; set; }

    public string Notes { get; set; }

    public DateOnly? NextVisit { get; set; }

    public virtual Pet Pet { get; set; }

    public virtual Staff Staff { get; set; }
}