// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE_PetWeb_API.Models;

public partial class Pet
{
    public int PetId { get; set; }

    public int UserId { get; set; }

    public string Name { get; set; }

    public string Species { get; set; }

    public string Breed { get; set; }

    public string Gender { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public decimal? Weight { get; set; }

    public string Color { get; set; }

    public string Description { get; set; }

    public string Photo { get; set; }

    public string MedicalHistory { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<MedicalRecord> MedicalRecords { get; set; } = new List<MedicalRecord>();

    public virtual ICollection<PetCareReminder> PetCareReminders { get; set; } = new List<PetCareReminder>();

    public virtual ICollection<PetGallery> PetGalleries { get; set; } = new List<PetGallery>();

    public virtual User User { get; set; }

    public virtual ICollection<Vaccination> Vaccinations { get; set; } = new List<Vaccination>();
}