// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE_PetWeb_API.Models;

public partial class PetCareReminder
{
    public int ReminderId { get; set; }

    public int PetId { get; set; }

    public string ReminderType { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime ReminderDate { get; set; }

    public string Frequency { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Pet Pet { get; set; }
}