// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE_PetWeb_API.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public int UserId { get; set; }

    public int? ServiceId { get; set; }

    public int? ProductId { get; set; }

    public int? AppointmentId { get; set; }

    public int? OrderId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public DateTime? ReviewDate { get; set; }

    public virtual Appointment Appointment { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }

    public virtual Service Service { get; set; }

    public virtual User User { get; set; }
}