// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE_PetWeb_API.Models;

public partial class StaffService
{
    public int StaffServiceId { get; set; }

    public int StaffId { get; set; }

    public int ServiceId { get; set; }

    public virtual Service Service { get; set; }

    public virtual Staff Staff { get; set; }
}