// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE_PetWeb_API.Models;

public partial class Vaccination
{
    public int VaccinationId { get; set; }

    public int PetId { get; set; }

    public string VaccineName { get; set; }

    public DateOnly VaccineDate { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public int? AdministeredBy { get; set; }

    public string Notes { get; set; }

    public virtual Staff AdministeredByNavigation { get; set; }

    public virtual Pet Pet { get; set; }
}